use std::{
    env, fs,
    io::{self, Write},
    path::{Path, PathBuf},
    thread::{self, JoinHandle},
    time::{SystemTime, UNIX_EPOCH},
};

use swayipc::{Connection, Event, EventType};

#[derive(Clone, Debug, PartialEq)]
pub struct OutputSnapshot {
    pub name: String,
    pub mode: Option<(i32, i32, i32)>,
    pub position: (i32, i32),
    pub scale: Option<f64>,
    pub transform: Option<String>,
}

pub fn render_outputs(outputs: &[OutputSnapshot]) -> io::Result<String> {
    if outputs.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "refusing to persist an empty Sway output state",
        ));
    }

    let mut outputs = outputs.to_vec();
    outputs.sort_by(|left, right| left.name.cmp(&right.name));

    let mut rendered = String::from(
        "# Generated by cosmolith from current Sway output state.\n\
         # Manual edits will be replaced.\n",
    );
    for output in outputs {
        rendered.push_str("output \"");
        rendered.push_str(&escape_sway_string(&output.name));
        rendered.push_str("\" enable");
        if let Some((width, height, refresh_millihz)) = output.mode
            && width > 0
            && height > 0
            && refresh_millihz > 0
        {
            rendered.push_str(&format!(
                " mode {width}x{height}@{}Hz",
                format_thousandths(refresh_millihz)
            ));
        }
        rendered.push_str(&format!(" pos {} {}", output.position.0, output.position.1));
        if let Some(scale) = output
            .scale
            .filter(|scale| scale.is_finite() && *scale > 0.0)
        {
            rendered.push_str(&format!(" scale {}", format_decimal(scale)));
        }
        if let Some(transform) = output.transform.filter(|value| is_sway_transform(value)) {
            rendered.push_str(" transform ");
            rendered.push_str(&transform);
        }
        rendered.push('\n');
    }
    Ok(rendered)
}

pub fn persist_outputs(path: &Path, outputs: &[OutputSnapshot]) -> io::Result<()> {
    let rendered = render_outputs(outputs)?;
    let parent = path.parent().ok_or_else(|| {
        io::Error::new(io::ErrorKind::InvalidInput, "output config has no parent")
    })?;
    fs::create_dir_all(parent)?;

    let temporary = temporary_path(path);
    let result = (|| {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        file.write_all(rendered.as_bytes())?;
        file.sync_all()?;
        fs::rename(&temporary, path)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

pub fn default_config_path() -> io::Result<PathBuf> {
    let home = env::var_os("HOME")
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME is not set"))?;
    Ok(PathBuf::from(home).join(".config/regolith3/sway/config.d/90_cosmic_outputs.conf"))
}

pub fn start_sway_output_persistence(path: PathBuf) -> JoinHandle<()> {
    thread::spawn(move || {
        let connection = match Connection::new() {
            Ok(connection) => connection,
            Err(error) => {
                eprintln!("Failed to connect to Sway output events: {error}");
                return;
            }
        };
        let events = match connection.subscribe([EventType::Output]) {
            Ok(events) => events,
            Err(error) => {
                eprintln!("Failed to subscribe to Sway output events: {error}");
                return;
            }
        };
        snapshot_on_start_and_output_events(
            events.map(|event| {
                event
                    .map(|event| matches!(event, Event::Output(_)))
                    .map_err(|error| error.to_string())
            }),
            || snapshot_to_path(&path),
        );
    })
}

fn snapshot_on_start_and_output_events<I, F>(events: I, mut snapshot: F)
where
    I: IntoIterator<Item = Result<bool, String>>,
    F: FnMut(),
{
    snapshot();
    for event in events {
        match event {
            Ok(true) => snapshot(),
            Ok(false) => {}
            Err(error) => eprintln!("Failed to read Sway output event: {error}"),
        }
    }
}

fn snapshot_to_path(path: &Path) {
    if let Err(error) = fetch_enabled_outputs().and_then(|outputs| persist_outputs(path, &outputs))
    {
        eprintln!("Failed to persist Sway output state: {error}");
    }
}

fn fetch_enabled_outputs() -> io::Result<Vec<OutputSnapshot>> {
    let outputs = Connection::new()
        .and_then(|mut connection| connection.get_outputs())
        .map_err(io::Error::other)?;
    Ok(outputs
        .into_iter()
        .filter(|output| output.active)
        .map(|output| OutputSnapshot {
            name: output.name,
            mode: output
                .current_mode
                .map(|mode| (mode.width, mode.height, mode.refresh)),
            position: (output.rect.x, output.rect.y),
            scale: output.scale,
            transform: output.transform,
        })
        .collect())
}

fn escape_sway_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\"', "\\\"")
}

fn format_thousandths(value: i32) -> String {
    format_decimal(f64::from(value) / 1000.0)
}

fn format_decimal(value: f64) -> String {
    let value = format!("{value:.3}");
    value.trim_end_matches('0').trim_end_matches('.').to_owned()
}

fn is_sway_transform(value: &str) -> bool {
    matches!(
        value,
        "normal" | "90" | "180" | "270" | "flipped" | "flipped-90" | "flipped-180" | "flipped-270"
    )
}

fn temporary_path(path: &Path) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("outputs.conf");
    path.with_file_name(format!(".{name}.{}.{}.tmp", std::process::id(), nonce))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn output(name: &str, x: i32) -> OutputSnapshot {
        OutputSnapshot {
            name: name.into(),
            mode: Some((1920, 1080, 60_000)),
            position: (x, 0),
            scale: Some(1.25),
            transform: Some("normal".into()),
        }
    }

    #[test]
    fn renders_deterministically_and_quotes_identifiers() {
        let rendered = render_outputs(&[output("DP 2\\\"dock", 1920), output("eDP-1", 0)]).unwrap();
        assert_eq!(
            rendered,
            "# Generated by cosmolith from current Sway output state.\n# Manual edits will be replaced.\noutput \"DP 2\\\\\\\"dock\" enable mode 1920x1080@60Hz pos 1920 0 scale 1.25 transform normal\noutput \"eDP-1\" enable mode 1920x1080@60Hz pos 0 0 scale 1.25 transform normal\n"
        );
    }

    #[test]
    fn rejects_empty_state_without_replacing_existing_file() {
        let path = temp_path("empty");
        fs::write(&path, "valid\n").unwrap();
        assert_eq!(
            persist_outputs(&path, &[]).unwrap_err().kind(),
            io::ErrorKind::InvalidData
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), "valid\n");
        let _ = fs::remove_file(path);
    }

    #[test]
    fn atomically_replaces_existing_file() {
        let dir = temp_path("replace-dir");
        let path = dir.join("90_cosmic_outputs.conf");
        fs::create_dir_all(&dir).unwrap();
        fs::write(&path, "old\n").unwrap();
        persist_outputs(&path, &[output("eDP-1", 0)]).unwrap();
        assert!(
            fs::read_to_string(&path)
                .unwrap()
                .contains("output \"eDP-1\"")
        );
        assert_eq!(fs::read_dir(&dir).unwrap().count(), 1);
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn failed_replacement_preserves_existing_file() {
        let dir = temp_path("failure-dir");
        let path = dir.join("target");
        fs::create_dir_all(&path).unwrap();
        fs::write(path.join("sentinel"), "valid").unwrap();
        assert!(persist_outputs(&path, &[output("eDP-1", 0)]).is_err());
        assert_eq!(fs::read_to_string(path.join("sentinel")).unwrap(), "valid");
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn snapshots_on_startup_and_each_successful_output_event() {
        let events = [
            Ok(true),
            Err("transient IPC failure".into()),
            Ok(false),
            Ok(true),
        ];
        let mut snapshots = 0;

        snapshot_on_start_and_output_events(events, || snapshots += 1);

        assert_eq!(snapshots, 3);
    }

    fn temp_path(label: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!(
            "cosmolith-{label}-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ))
    }
}
