//! Persist Sway output profiles through Regolith's existing generated include.
//!
//! This is the Sway-backed Regolith compatibility bridge: cosmic-comp remains
//! the native output applier, while COSMOLith observes Sway's resulting profile
//! and records it for the next Sway config load. It is not a wlr-output-
//! management client and does not apply output state itself.

use std::{
    fs,
    io::{self, Write},
    os::unix::fs::{OpenOptionsExt, PermissionsExt},
    path::{Path, PathBuf},
    thread::{self, JoinHandle},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use swayipc::{Connection, Event, EventType};

const DISPLAY_CONFIG: &str = "display.conf";

#[derive(Clone, Debug, PartialEq)]
pub struct OutputSnapshot {
    pub name: String,
    pub active: bool,
    pub mode: Option<(i32, i32, i32)>,
    pub position: (i32, i32),
    pub scale: Option<f64>,
    pub transform: Option<String>,
}

pub fn config_path() -> PathBuf {
    crate::persistence::generated_config_dir().join(DISPLAY_CONFIG)
}

fn from_sway_output(output: &swayipc::Output) -> OutputSnapshot {
    OutputSnapshot {
        name: output.name.clone(),
        active: output.active,
        mode: output
            .current_mode
            .map(|mode| (mode.width, mode.height, mode.refresh)),
        position: (output.rect.x, output.rect.y),
        scale: output.scale,
        transform: output.transform.clone(),
    }
}

fn invalid(message: &str) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message)
}

pub fn render_outputs(outputs: &[OutputSnapshot]) -> String {
    let mut outputs = outputs.to_vec();
    outputs.sort_by(|left, right| left.name.cmp(&right.name));
    let mut rendered = String::from(
        "# Generated by cosmolith. Do not edit by hand; changes will be overwritten.\n",
    );
    for output in outputs {
        rendered.push_str("output \"");
        rendered.push_str(&escape(&output.name));
        if !output.active {
            rendered.push_str("\" disable\n");
            continue;
        }
        rendered.push_str("\" enable");
        if let Some((width, height, refresh)) = output.mode
            && width > 0
            && height > 0
            && refresh > 0
        {
            rendered.push_str(&format!(
                " mode {width}x{height}@{}Hz",
                decimal(refresh as f64 / 1000.0)
            ));
        }
        rendered.push_str(&format!(" pos {} {}", output.position.0, output.position.1));
        if let Some(scale) = output
            .scale
            .filter(|scale| scale.is_finite() && *scale > 0.0)
        {
            rendered.push_str(&format!(" scale {}", decimal(scale)));
        }
        if let Some(transform) = output.transform.filter(|value| valid_transform(&value)) {
            rendered.push_str(&format!(" transform {transform}"));
        }
        rendered.push('\n');
    }
    rendered
}

pub fn persist_outputs(path: &Path, outputs: &[OutputSnapshot]) -> io::Result<bool> {
    if outputs.is_empty() {
        return Err(invalid("refusing to persist empty output state"));
    }
    let rendered = render_outputs(outputs);
    if matches!(fs::read_to_string(path), Ok(contents) if contents == rendered) {
        return Ok(false);
    }
    let parent = path
        .parent()
        .ok_or_else(|| invalid("config has no parent"))?;
    fs::create_dir_all(parent)?;
    let mode = fs::metadata(path)
        .map(|metadata| metadata.permissions().mode() & 0o666)
        .unwrap_or(0o600);
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let temporary = path.with_file_name(format!(
        ".{}.{}.tmp",
        path.file_name().unwrap().to_string_lossy(),
        nonce
    ));
    let result = (|| {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temporary)?;
        file.set_permissions(fs::Permissions::from_mode(mode))?;
        file.write_all(rendered.as_bytes())?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        fs::File::open(parent)?.sync_all()
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result.map(|()| true)
}

const MAX_RECONNECT_DELAY: Duration = Duration::from_secs(16);

pub fn start_output_watcher(path: PathBuf) -> JoinHandle<()> {
    thread::spawn(move || retry_subscription(&path))
}

fn retry_subscription(path: &Path) {
    let mut failures = 0u32;
    loop {
        match run_subscription(path) {
            Ok(()) => return,
            Err(error) => eprintln!("Sway output watcher restarting: {error}"),
        }
        let delay = Duration::from_secs(1)
            .saturating_mul(1u32 << failures.min(4))
            .min(MAX_RECONNECT_DELAY);
        thread::sleep(delay);
        failures = failures.saturating_add(1);
    }
}

fn run_subscription(path: &Path) -> Result<(), String> {
    let connection = Connection::new().map_err(|error| error.to_string())?;
    let events = connection
        .subscribe([EventType::Output])
        .map_err(|error| error.to_string())?;
    consume_events(
        events.map(|event| {
            event
                .map(|event| matches!(event, Event::Output(_)))
                .map_err(|error| error.to_string())
        }),
        || persist_current(path),
    )
}

fn consume_events<I, F>(events: I, mut snapshot: F) -> Result<(), String>
where
    I: IntoIterator<Item = Result<bool, String>>,
    F: FnMut(),
{
    snapshot();
    for event in events {
        match event {
            Ok(true) => snapshot(),
            Ok(false) => {}
            Err(error) => return Err(error),
        }
    }
    Err("Sway output event stream ended".into())
}

fn persist_current(path: &Path) {
    let result = Connection::new()
        .and_then(|mut connection| connection.get_outputs())
        .map_err(io::Error::other)
        .and_then(|outputs| {
            persist_outputs(
                path,
                &outputs.iter().map(from_sway_output).collect::<Vec<_>>(),
            )
            .map(|_| ())
        });
    if let Err(error) = result {
        eprintln!("Failed to persist Sway output profile: {error}");
    }
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn decimal(value: f64) -> String {
    format!("{value:.3}")
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string()
}

fn valid_transform(value: &str) -> bool {
    matches!(
        value,
        "normal" | "90" | "180" | "270" | "flipped" | "flipped-90" | "flipped-180" | "flipped-270"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::persistence::test_support::TempConfigHome;
    use std::fs;

    fn output(name: &str, x: i32) -> OutputSnapshot {
        OutputSnapshot {
            name: name.into(),
            active: true,
            mode: Some((1920, 1080, 60000)),
            position: (x, 0),
            scale: Some(1.25),
            transform: Some("normal".into()),
        }
    }

    #[test]
    fn renders_sorted_profiles_deterministically() {
        let mut disabled = output("HDMI-A-1", 1920);
        disabled.active = false;
        disabled.mode = None;
        assert_eq!(
            render_outputs(&[disabled, output("eDP-1", 0)]),
            "# Generated by cosmolith. Do not edit by hand; changes will be overwritten.\noutput \"HDMI-A-1\" disable\noutput \"eDP-1\" enable mode 1920x1080@60Hz pos 0 0 scale 1.25 transform normal\n"
        );
    }

    #[test]
    fn uses_existing_regolith_generated_config_path() {
        let home = TempConfigHome::new();
        assert_eq!(
            config_path(),
            home.path
                .join("regolith3/sway/cosmic-settings/generated-config.d/display.conf")
        );
    }

    #[test]
    fn atomic_write_skips_identical_profile() {
        let _home = TempConfigHome::new();
        let path = config_path();
        assert!(persist_outputs(&path, &[output("eDP-1", 0)]).unwrap());
        let first = fs::read_to_string(&path).unwrap();
        assert!(!persist_outputs(&path, &[output("eDP-1", 0)]).unwrap());
        assert_eq!(fs::read_to_string(path).unwrap(), first);
    }

    #[test]
    fn empty_state_refuses_to_replace_existing_file() {
        let _home = TempConfigHome::new();
        let path = config_path();
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "existing\n").unwrap();
        assert!(persist_outputs(&path, &[]).is_err());
        assert_eq!(fs::read_to_string(path).unwrap(), "existing\n");
    }

    #[test]
    fn snapshots_on_start_and_output_events_only() {
        let events = [Ok(false), Ok(true), Err("transient".into()), Ok(true)];
        let mut snapshots = 0;
        assert!(consume_events(events, || snapshots += 1).is_err());
        assert_eq!(snapshots, 2);
    }
}
