use std::{
    env, fs,
    io::{self, Write},
    os::unix::fs::{OpenOptionsExt, PermissionsExt},
    path::{Path, PathBuf},
    thread::{self, JoinHandle},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use swayipc::{Connection, Event, EventType};

const MAX_RECONNECT_DELAY: Duration = Duration::from_secs(16);

#[derive(Clone, Debug, PartialEq)]
pub struct OutputSnapshot {
    pub name: String,
    pub active: bool,
    pub mode: Option<(i32, i32, i32)>,
    pub position: (i32, i32),
    pub scale: Option<f64>,
    pub transform: Option<String>,
}

pub fn render_outputs(outputs: &[OutputSnapshot]) -> io::Result<String> {
    let mut outputs = outputs.to_vec();
    outputs.sort_by(|left, right| left.name.cmp(&right.name));

    let mut rendered = String::from(
        "# Generated by cosmolith from current Sway output state.\n\
         # Manual edits will be replaced.\n",
    );
    for output in outputs {
        rendered.push_str("output \"");
        rendered.push_str(&escape_sway_string(&output.name));
        if !output.active {
            rendered.push_str("\" disable\n");
            continue;
        }
        rendered.push_str("\" enable");
        if let Some((width, height, refresh_millihz)) = output.mode
            && width > 0
            && height > 0
            && refresh_millihz > 0
        {
            rendered.push_str(&format!(
                " mode {width}x{height}@{}Hz",
                format_thousandths(refresh_millihz)
            ));
        }
        rendered.push_str(&format!(" pos {} {}", output.position.0, output.position.1));
        if let Some(scale) = output
            .scale
            .filter(|scale| scale.is_finite() && *scale > 0.0)
        {
            rendered.push_str(&format!(" scale {}", format_decimal(scale)));
        }
        if let Some(transform) = output.transform.filter(|value| is_sway_transform(value)) {
            rendered.push_str(" transform ");
            rendered.push_str(&transform);
        }
        rendered.push('\n');
    }
    Ok(rendered)
}

pub fn persist_outputs(path: &Path, outputs: &[OutputSnapshot]) -> io::Result<()> {
    if outputs.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "refusing to persist an empty Sway output topology",
        ));
    }

    let rendered = render_outputs(outputs)?;
    let parent = path.parent().ok_or_else(|| {
        io::Error::new(io::ErrorKind::InvalidInput, "output config has no parent")
    })?;
    fs::create_dir_all(parent)?;

    let mode = fs::metadata(path)
        .map(|metadata| metadata.permissions().mode() & 0o666)
        .unwrap_or(0o600);
    let temporary = temporary_path(path);
    let result = (|| {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temporary)?;
        file.set_permissions(fs::Permissions::from_mode(mode))?;
        file.write_all(rendered.as_bytes())?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        fs::File::open(parent)?.sync_all()
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

pub fn default_config_path() -> io::Result<PathBuf> {
    config_path(env::var_os("XDG_CONFIG_HOME"), env::var_os("HOME"))
}

pub fn config_path(
    xdg_config_home: Option<std::ffi::OsString>,
    home: Option<std::ffi::OsString>,
) -> io::Result<PathBuf> {
    let config = xdg_config_home
        .map(PathBuf::from)
        .or_else(|| home.map(|home| PathBuf::from(home).join(".config")))
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::NotFound,
                "neither XDG_CONFIG_HOME nor HOME is set",
            )
        })?;
    Ok(config.join("regolith3/sway/config.d/90_cosmic_outputs.conf"))
}

pub fn start_sway_output_persistence(path: PathBuf) -> JoinHandle<()> {
    thread::spawn(move || {
        retry_subscriber(
            Duration::from_secs(1),
            || run_subscription(&path),
            thread::sleep,
        );
    })
}

fn run_subscription(path: &Path) -> Result<(), String> {
    let connection = match Connection::new() {
        Ok(connection) => connection,
        Err(error) => {
            return Err(format!("failed to connect to Sway output events: {error}"));
        }
    };
    let events = match connection.subscribe([EventType::Output]) {
        Ok(events) => events,
        Err(error) => {
            return Err(format!(
                "failed to subscribe to Sway output events: {error}"
            ));
        }
    };
    snapshot_to_path(path);
    for event in events {
        match event {
            Ok(Event::Output(_)) => snapshot_to_path(path),
            Ok(_) => {}
            Err(error) => return Err(format!("failed to read Sway output event: {error}")),
        }
    }
    Err("Sway output event stream ended".into())
}

fn retry_subscriber<R, S>(base_delay: Duration, mut run: R, mut sleep: S)
where
    R: FnMut() -> Result<(), String>,
    S: FnMut(Duration),
{
    let mut failures = 0u32;
    loop {
        match run() {
            Ok(()) => return,
            Err(error) => eprintln!("Sway output subscriber restarting: {error}"),
        }
        let multiplier = 1u32.checked_shl(failures.min(4)).unwrap_or(16);
        sleep(
            base_delay
                .saturating_mul(multiplier)
                .min(MAX_RECONNECT_DELAY),
        );
        failures = failures.saturating_add(1);
    }
}

fn snapshot_to_path(path: &Path) {
    if let Err(error) = fetch_enabled_outputs().and_then(|outputs| persist_outputs(path, &outputs))
    {
        eprintln!("Failed to persist Sway output state: {error}");
    }
}

fn fetch_enabled_outputs() -> io::Result<Vec<OutputSnapshot>> {
    let outputs = Connection::new()
        .and_then(|mut connection| connection.get_outputs())
        .map_err(io::Error::other)?;
    Ok(outputs
        .into_iter()
        .map(|output| OutputSnapshot {
            name: output.name,
            active: output.active,
            mode: output
                .current_mode
                .map(|mode| (mode.width, mode.height, mode.refresh)),
            position: (output.rect.x, output.rect.y),
            scale: output.scale,
            transform: output.transform,
        })
        .collect())
}

fn escape_sway_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\"', "\\\"")
}

fn format_thousandths(value: i32) -> String {
    format_decimal(f64::from(value) / 1000.0)
}

fn format_decimal(value: f64) -> String {
    let value = format!("{value:.3}");
    value.trim_end_matches('0').trim_end_matches('.').to_owned()
}

fn is_sway_transform(value: &str) -> bool {
    matches!(
        value,
        "normal" | "90" | "180" | "270" | "flipped" | "flipped-90" | "flipped-180" | "flipped-270"
    )
}

fn temporary_path(path: &Path) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("outputs.conf");
    path.with_file_name(format!(".{name}.{}.{}.tmp", std::process::id(), nonce))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn output(name: &str, x: i32) -> OutputSnapshot {
        OutputSnapshot {
            name: name.into(),
            active: true,
            mode: Some((1920, 1080, 60_000)),
            position: (x, 0),
            scale: Some(1.25),
            transform: Some("normal".into()),
        }
    }

    #[test]
    fn renders_deterministically_and_quotes_identifiers() {
        let rendered = render_outputs(&[output("DP 2\\\"dock", 1920), output("eDP-1", 0)]).unwrap();
        assert_eq!(
            rendered,
            "# Generated by cosmolith from current Sway output state.\n# Manual edits will be replaced.\noutput \"DP 2\\\\\\\"dock\" enable mode 1920x1080@60Hz pos 1920 0 scale 1.25 transform normal\noutput \"eDP-1\" enable mode 1920x1080@60Hz pos 0 0 scale 1.25 transform normal\n"
        );
    }

    #[test]
    fn renders_active_and_disabled_outputs_as_complete_topology() {
        let mut disabled = output("HDMI-A-1", 1920);
        disabled.active = false;
        disabled.mode = None;

        let rendered = render_outputs(&[disabled, output("eDP-1", 0)]).unwrap();

        assert!(rendered.contains("output \"HDMI-A-1\" disable\n"));
        assert!(rendered.contains("output \"eDP-1\" enable mode 1920x1080@60Hz"));
    }

    #[test]
    fn renderer_allows_empty_input_but_persistence_rejects_empty_topology() {
        assert!(
            render_outputs(&[])
                .unwrap()
                .starts_with("# Generated by cosmolith")
        );
        let path = temp_path("empty-renderer");
        assert_eq!(
            persist_outputs(&path, &[]).unwrap_err().kind(),
            io::ErrorKind::InvalidData
        );
    }

    #[test]
    fn rejects_empty_state_without_replacing_existing_file() {
        let path = temp_path("empty");
        fs::write(&path, "valid\n").unwrap();
        assert_eq!(
            persist_outputs(&path, &[]).unwrap_err().kind(),
            io::ErrorKind::InvalidData
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), "valid\n");
        let _ = fs::remove_file(path);
    }

    #[test]
    fn atomically_replaces_existing_file() {
        let dir = temp_path("replace-dir");
        let path = dir.join("90_cosmic_outputs.conf");
        fs::create_dir_all(&dir).unwrap();
        fs::write(&path, "old\n").unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o741)).unwrap();
        persist_outputs(&path, &[output("eDP-1", 0)]).unwrap();
        assert!(
            fs::read_to_string(&path)
                .unwrap()
                .contains("output \"eDP-1\"")
        );
        assert_eq!(fs::read_dir(&dir).unwrap().count(), 1);
        assert_eq!(
            fs::metadata(&path).unwrap().permissions().mode() & 0o777,
            0o640
        );
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn new_file_uses_private_permissions() {
        let dir = temp_path("new-mode-dir");
        let path = dir.join("outputs.conf");
        persist_outputs(&path, &[output("eDP-1", 0)]).unwrap();
        assert_eq!(
            fs::metadata(&path).unwrap().permissions().mode() & 0o777,
            0o600
        );
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn failed_replacement_preserves_existing_file() {
        let dir = temp_path("failure-dir");
        let path = dir.join("target");
        fs::create_dir_all(&path).unwrap();
        fs::write(path.join("sentinel"), "valid").unwrap();
        assert!(persist_outputs(&path, &[output("eDP-1", 0)]).is_err());
        assert_eq!(fs::read_to_string(path.join("sentinel")).unwrap(), "valid");
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn retries_with_bounded_backoff_until_restart_succeeds() {
        let mut attempts = 0;
        let mut delays = Vec::new();
        retry_subscriber(
            Duration::from_secs(1),
            || {
                attempts += 1;
                if attempts < 7 {
                    Err("subscriber ended".into())
                } else {
                    Ok(())
                }
            },
            |delay| delays.push(delay),
        );
        assert_eq!(attempts, 7);
        assert_eq!(delays, [1, 2, 4, 8, 16, 16].map(Duration::from_secs));
    }

    #[test]
    fn successful_subscription_stops_retrying_without_sleeping() {
        let mut attempts = 0;
        let mut delays = Vec::new();
        retry_subscriber(
            Duration::from_millis(10),
            || {
                attempts += 1;
                Ok(())
            },
            |delay| delays.push(delay),
        );
        assert_eq!(attempts, 1);
        assert!(delays.is_empty());
    }

    #[test]
    fn config_path_prefers_xdg_then_falls_back_to_home() {
        assert_eq!(
            config_path(Some("/xdg".into()), Some("/home/user".into())).unwrap(),
            PathBuf::from("/xdg/regolith3/sway/config.d/90_cosmic_outputs.conf")
        );
        assert_eq!(
            config_path(None, Some("/home/user".into())).unwrap(),
            PathBuf::from("/home/user/.config/regolith3/sway/config.d/90_cosmic_outputs.conf")
        );
        assert_eq!(
            config_path(None, None).unwrap_err().kind(),
            io::ErrorKind::NotFound
        );
    }

    fn temp_path(label: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!(
            "cosmolith-{label}-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ))
    }
}
