//! Persistence for cosmolith-generated Sway input configuration.
//!
//! The proposal committed cosmolith to writing generated Sway config
//! snippets to `generated-config.d/` so that settings survive a Sway
//! restart/reboot even if cosmolith itself is not running to replay the
//! live cosmic-config state. Regolith's own Sway root config already
//! contains:
//!
//! ```text
//! include $HOME/.config/regolith3/sway/cosmic-settings/generated-config.d/*
//! ```
//!
//! (see `regolith-wm-config/etc/regolith/sway/config`), so any file this
//! module writes there is automatically merged into Sway's runtime config on
//! the next Sway start or `swaymsg reload`. Prior to this module, nothing in
//! cosmolith ever wrote to that directory (`grep -rn "generated-config"
//! src/` returned zero hits) even though every input change was already
//! phrased as a `input <target> <setting> <value>` Sway command, which is
//! *also* valid Sway config-file syntax - the same line can be sent over
//! IPC and dropped into a config snippet unchanged.

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::PathBuf;

const GENERATED_CONFIG_SUBPATH: &str = "regolith3/sway/cosmic-settings/generated-config.d";
const INPUT_CONF_FILENAME: &str = "input.conf";

/// Resolve the directory where generated Sway config snippets are
/// persisted. Honors `$XDG_CONFIG_HOME` (used by tests to isolate from the
/// real user config) and otherwise falls back to `$HOME/.config`, matching
/// the path committed in the proposal:
/// `~/.config/regolith3/sway/cosmic-settings/generated-config.d/`.
pub fn generated_config_dir() -> PathBuf {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            let home = std::env::var_os("HOME").expect("HOME must be set");
            PathBuf::from(home).join(".config")
        });
    base.join(GENERATED_CONFIG_SUBPATH)
}

fn input_conf_path() -> PathBuf {
    generated_config_dir().join(INPUT_CONF_FILENAME)
}

/// Identifies one persisted `input <target> <setting> ...` directive so a
/// later change to the same setting overwrites the old line instead of
/// accumulating duplicates.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct DirectiveKey {
    target: String,
    setting: String,
}

/// Record a raw `input <target> <setting> <value...>` Sway directive,
/// merging it into the on-disk `generated-config.d/input.conf` snippet.
///
/// `line` must be the exact command already sent to Sway over IPC (e.g.
/// `"input type:touchpad tap enabled"`), since that is also valid Sway
/// config-file syntax and can be included verbatim.
pub fn record_input_line(line: &str) -> io::Result<()> {
    let Some(key) = parse_key(line) else {
        // Not a well-formed `input <target> <setting> ...` line (for
        // example a bindsym command routed through the same call site);
        // nothing to persist.
        return Ok(());
    };
    let mut directives = load_raw_directives().unwrap_or_default();
    directives.insert(key, line.trim().to_string());
    write_raw_directives(&directives)
}

fn parse_key(line: &str) -> Option<DirectiveKey> {
    let mut parts = line.trim().splitn(4, ' ');
    if parts.next()? != "input" {
        return None;
    }
    let target = parts.next()?.to_string();
    let setting = parts.next()?.to_string();
    Some(DirectiveKey { target, setting })
}

fn write_raw_directives(directives: &BTreeMap<DirectiveKey, String>) -> io::Result<()> {
    let dir = generated_config_dir();
    fs::create_dir_all(&dir)?;
    let mut contents = String::from(
        "# Generated by cosmolith. Do not edit by hand; changes will be overwritten.\n",
    );
    for line in directives.values() {
        contents.push_str(line);
        contents.push('\n');
    }
    // Write-then-rename so a concurrent Sway config reload never observes a
    // partially written file.
    let tmp_path = dir.join(format!("{INPUT_CONF_FILENAME}.tmp"));
    fs::write(&tmp_path, contents)?;
    fs::rename(&tmp_path, input_conf_path())?;
    Ok(())
}

fn load_raw_directives() -> io::Result<BTreeMap<DirectiveKey, String>> {
    let contents = match fs::read_to_string(input_conf_path()) {
        Ok(c) => c,
        Err(err) if err.kind() == io::ErrorKind::NotFound => return Ok(BTreeMap::new()),
        Err(err) => return Err(err),
    };
    let mut directives = BTreeMap::new();
    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(key) = parse_key(line) {
            directives.insert(key, line.to_string());
        }
    }
    Ok(directives)
}

/// Load every persisted directive, in file order, as raw Sway command
/// strings (`"input type:touchpad tap enabled"`, etc).
///
/// Used both by tests to assert what was persisted, and at cosmolith
/// start-up to replay saved settings back over the live Sway IPC
/// connection, so a cosmolith restart recovers the last-known state even
/// before cosmic-config re-emits it.
pub fn load_input_lines() -> io::Result<Vec<String>> {
    Ok(load_raw_directives()?.into_values().collect())
}

/// Replay every persisted directive through `apply` (typically a Sway IPC
/// `run_command` closure). Returns the number of directives replayed.
pub fn replay_into(mut apply: impl FnMut(&str) -> io::Result<()>) -> io::Result<usize> {
    let lines = load_input_lines()?;
    let count = lines.len();
    for line in lines {
        apply(&line)?;
    }
    Ok(count)
}

// Test-only helper shared with other modules (e.g. `compositor::sway`) that
// need to isolate `XDG_CONFIG_HOME` while asserting what got written to
// `generated-config.d`. Kept `pub(crate)` (rather than private to `mod
// tests` below) specifically so those other modules' tests serialize on the
// same lock instead of racing on the same process-global env var.
#[cfg(test)]
pub(crate) mod test_support {
    use std::path::PathBuf;
    use std::sync::Mutex;

    // `XDG_CONFIG_HOME` is process-global state; serialize tests that touch
    // it so they can't interleave.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    pub(crate) struct TempConfigHome {
        pub(crate) path: PathBuf,
        _guard: std::sync::MutexGuard<'static, ()>,
    }

    impl TempConfigHome {
        pub(crate) fn new() -> Self {
            let guard = ENV_LOCK.lock().unwrap_or_else(|poison| poison.into_inner());
            let path = std::env::temp_dir().join(format!(
                "cosmolith-generated-config-test-{}-{}",
                std::process::id(),
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            ));
            // Safety: guarded by ENV_LOCK, no other thread reads/writes
            // XDG_CONFIG_HOME while this guard is held.
            unsafe { std::env::set_var("XDG_CONFIG_HOME", &path) };
            Self {
                path,
                _guard: guard,
            }
        }
    }

    impl Drop for TempConfigHome {
        fn drop(&mut self) {
            unsafe { std::env::remove_var("XDG_CONFIG_HOME") };
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::test_support::TempConfigHome;
    use super::*;

    #[test]
    fn generated_config_dir_matches_committed_proposal_path() {
        let home = TempConfigHome::new();
        let dir = generated_config_dir();
        assert_eq!(
            dir,
            home.path
                .join("regolith3/sway/cosmic-settings/generated-config.d")
        );
    }

    #[test]
    fn write_then_restart_merges_persisted_directive_into_runtime_config() {
        let _home = TempConfigHome::new();

        // No settings changed yet: nothing on disk, nothing to replay.
        assert!(load_input_lines().unwrap().is_empty());

        // Simulate cosmolith applying a touchpad tap-enabled change: it
        // persists the exact directive it sent to Sway over IPC.
        record_input_line("input type:touchpad tap enabled").unwrap();

        let path = generated_config_dir().join("input.conf");
        assert!(
            path.exists(),
            "generated-config.d/input.conf was not written to the committed path"
        );

        // Simulate a Sway/cosmolith restart: a fresh process only has the
        // on-disk snippet to recover state from. `replay_into` is what
        // cosmolith calls at start-up (and what Sway's own `include` line
        // does implicitly) to merge it back into the runtime config.
        let mut replayed = Vec::new();
        let count = replay_into(|line| {
            replayed.push(line.to_string());
            Ok(())
        })
        .unwrap();

        assert_eq!(count, 1);
        assert_eq!(
            replayed,
            vec!["input type:touchpad tap enabled".to_string()],
            "persisted directive was not merged back into runtime config after restart"
        );
    }

    #[test]
    fn later_change_to_same_setting_overwrites_instead_of_duplicating() {
        let _home = TempConfigHome::new();

        record_input_line("input type:touchpad tap enabled").unwrap();
        record_input_line("input type:touchpad tap disabled").unwrap();

        let lines = load_input_lines().unwrap();
        assert_eq!(lines, vec!["input type:touchpad tap disabled".to_string()]);
    }

    #[test]
    fn unrelated_commands_are_not_persisted() {
        let _home = TempConfigHome::new();

        record_input_line("bindsym Mod4+d exec cosmic-launcher").unwrap();

        assert!(load_input_lines().unwrap().is_empty());
        assert!(!generated_config_dir().join("input.conf").exists());
    }
}
